//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiSign.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class signer_history
    {
        [Key]
        public int id { get; set; }
        public string files { get; set; }
        public string activity { get; set; }
        public string type { get; set; }
        public Nullable<System.DateTime> time_ { get; set; }
    }
}
