//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiSign.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class signer_workflow
    {
        [Key]
        public int workflow_id { get; set; }
        public Nullable<int> request_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public string document { get; set; }
        public string signing_key { get; set; }
        public string positions { get; set; }
        public string chain_positions { get; set; }
        public string chain_emails { get; set; }
        public string sender_note { get; set; }
        public string email { get; set; }
        public string status { get; set; }
        public string notes { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<int> order_by { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string face_auth_id { get; set; }
        public string face_auth_status { get; set; }
        public string face_auth_payload { get; set; }
    }
}
