//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiSign.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class signer_requests
    {
        [Key]
        public int id { get; set; }
        public Nullable<int> company { get; set; }
        public string sender { get; set; }
        public string sender_note { get; set; }
        public Nullable<System.DateTime> send_time { get; set; }
        public string status { get; set; }
        public string workflow_method { get; set; }
        public Nullable<int> next_order { get; set; }
        public string requestor_email { get; set; }
        public string department_id { get; set; }
        public Nullable<int> classification_id { get; set; }
        public Nullable<System.DateTime> created_time { get; set; }
        public string pdf_certified { get; set; }
        public Nullable<int> sender_old { get; set; }
        public string reason { get; set; }
    }
}
