//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiSign.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class signer_logs
    {
        public string activity { get; set; }
        public System.DateTime time_ { get; set; }
        public string ip_address { get; set; }
        public Nullable<int> users { get; set; }
        public string uri { get; set; }
        [Key]
        public int id { get; set; }
    }
}
